baseURL = "https://comparatifs.netlify.app/"
languageCode = "en-us"
title = "Le Top des Comparatifs 2025"
theme = "PaperMod"
enableGitInfo = true
unsafe = true

[params]
  ShowReadingTime = true
  ShowShareButtons = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
